In [1]:
data_root = '/home/scott/Documents/SPEC_Spider'

In [2]:
!tree /home/scott/Documents/SPEC_Spider

/home/scott/Documents/SPEC_Spider
├── cpu
│   ├── cpu2006
│   │   ├── SPECfp.csv
│   │   ├── SPECfp_rate.csv
│   │   ├── SPECint.csv
│   │   └── SPECint_rate.csv
│   └── cpu2017
│       ├── CFP2017_rate.csv
│       ├── CFP2017_speed.csv
│       ├── CINT2017_rate.csv
│       └── CINT2017_speed.csv
├── java
│   ├── jbb2015
│   │   ├── SPECjbb2015-Composite.csv
│   │   ├── SPECjbb2015-Distributed.csv
│   │   └── SPECjbb2015-MultiJVM.csv
│   └── jvm2008
│       └── jvm2008.csv
├── jbb2015.csv
└── power
    └── ssj2008.csv

7 directories, 14 files


In [3]:
import pandas as pd
import numpy as np
import re

In [4]:
ssj2008 = pd.read_csv(f"{data_root}/power/ssj2008.csv")

In [5]:
ssj2008.columns

Index(['Suite', 'Test Sponsor', 'SPEC License #', 'Test Method', 'Tested By',
       'Test Date', 'Hardware Availability', 'Software Availability',
       'Publication', 'ssj_ops @ 100% of target load',
       'Average watts @ 100% of target load',
       'Performance/power @ 100% of target load',
       'ssj_ops @ 90% of target load', 'Average watts @ 90% of target load',
       'Performance/power @ 90% of target load',
       'ssj_ops @ 80% of target load', 'Average watts @ 80% of target load',
       'Performance/power @ 80% of target load',
       'ssj_ops @ 70% of target load', 'Average watts @ 70% of target load',
       'Performance/power @ 70% of target load',
       'ssj_ops @ 60% of target load', 'Average watts @ 60% of target load',
       'Performance/power @ 60% of target load',
       'ssj_ops @ 50% of target load', 'Average watts @ 50% of target load',
       'Performance/power @ 50% of target load',
       'ssj_ops @ 40% of target load', 'Average watts @ 40% of target l

In [6]:
ssj2008_columns = [
    'Suite', 'Hardware Vendor', 'Model', 'Test Date',
    'Hardware Availability', 'Benchmark',
    'CPU Name', 'CPU Characteristics', 'CPU Frequency (MHz)', 'CPU(s) Enabled',
    'Hardware Threads', 'CPU(s) Orderable', 'Primary Cache', 'Secondary Cache', 'Tertiary Cache',
    'Memory Amount (GB)', '# and size of DIMM', 'Memory Details', 'Disk Drive',
    'Operating System (OS)', 'OS Version', 'Filesystem',
    'JVM Vendor', 'JVM Version',
    'URL Suffix'
]

In [8]:
ssj2008 = ssj2008[ssj2008_columns]

In [10]:
ssj2008.shape

(778, 25)

In [13]:
ssj2008 = ssj2008[~ssj2008.isnull().any(axis=1)].reset_index(drop=True)

In [12]:
ssj2008.shape

(778, 25)

In [39]:

ssj2008['Total Cores'] = ssj2008['CPU Enabled'].apply(lambda x: int(x.split(',')[0].split()[0]))

In [41]:
ssj2008['Chips'] = ssj2008['CPU Enabled'].apply(lambda x: int(x.split(',')[1].split()[0]))

In [42]:
ssj2008['Cores Per Chip'] = ssj2008['CPU Enabled'].apply(lambda x: int(x.split(',')[2].split()[0]))

In [49]:
ssj2008['Total Threads'].apply(lambda x: int(re.sub(' / core', '', re.findall('\d+ / core', x)[0]))).unique()

array([2, 1, 4])

In [52]:
ssj2008[ssj2008['Test Date'] == 'Various'].iloc[0]

Suite                                                  SPECpower_ssj2008
HW Vendor                                              Acer Incorporated
System Name                                       Acer AW2000h-AW170h F1
Test Date                                                        Various
HW Avail                                                        Feb-2011
Result                                                             2,769
CPU Name                                                Intel Xeon X5675
CPU Characteristics                   Six-Core, 3.07 GHz, 12 MB L3 cache
CPU MHz                                                             3067
CPU Enabled                              12 cores, 2 chips, 6 cores/chip
Total Threads                                              24 (2 / core)
CPU Orderable                                                  1,2 chips
L1 Cache                              32 KB I + 32 KB D on chip per core
L2 Cache                                     256 KB

In [50]:
ssj2008['Test Date'].unique()

array(['Sep 26, 2018', 'Oct 20, 2010', 'Oct 5, 2010', 'Sep 29, 2010',
       'Oct 8, 2010', 'Aug 17, 2010', 'Aug 5, 2010', 'Sep 10, 2010',
       'Sep 14, 2010', 'Aug 19, 2010', 'Aug 20, 2010', 'Jul 26, 2010',
       'May 28, 2010', 'Apr 24, 2009', 'Aug 4, 2009', 'Aug 11, 2009',
       'Sep 16, 2021', 'Sep 15, 2021', 'May 4, 2009', 'Feb 1, 2021',
       'Nov 7, 2012', 'Nov 8, 2012', 'Nov 6, 2012', 'Oct 17, 2008',
       'Oct 16, 2008', 'Dec 19, 2008', 'Aug 5, 2008', 'Aug 4, 2008',
       'Apr 22, 2021', 'May 27, 2021', 'Sep 7, 2019', 'Apr 15, 2019',
       'Dec 20, 2018', 'Jan 6, 2019', 'Aug 24, 2018', 'Jul 15, 2018',
       'Sep 25, 2014', 'Jun 28, 2012', 'Jun 19, 2012', 'Jun 12, 2012',
       'Sep 12, 2008', 'Oct 15, 2012', 'Oct 11, 2012', 'Apr 25, 2002',
       'Sep 23, 2011', 'Sep 13, 2011', 'May 26, 2012', 'May 24, 2012',
       'Nov 28, 2007', 'Jan 11, 2008', 'Nov 27, 2007', 'Jan 10, 2008',
       'Apr 20, 2009', 'Apr 17, 2009', 'Mar 10, 2009', 'Apr 23, 2018',
       'May 27, 201

In [46]:
ssj2008['Total Threads'].unique()

array(['112 (2 / core)', '24 (1 / core)', '6 (1 / core)', '24 (2 / core)',
       '12 (1 / core)', '8 (1 / core)', '16 (2 / core)', '40 (2 / core)',
       '16 (1 / core)', '160 (2 / core)', '256 (2 / core)',
       '128 (2 / core)', '72 (2 / core)', '32 (2 / core)',
       '32 (1 / core)', '4 (1 / core)', '56 (2 / core)', '88 (2 / core)',
       '64 (2 / core)', '96 (2 / core)', '8 (2 / core)', '224 (2 / core)',
       '4 (2 / core)', '448 (2 / core)', '12 (2 / core)', '48 (2 / core)',
       '152 (2 / core)', '144 (2 / core)', '2 (1 / core)',
       '64 (1 / core)', '80 (2 / core)', '48 (1 / core)',
       '176 (2 / core)', '32 (4 / core)'], dtype=object)

In [44]:
ssj2008[~ssj2008['Cores Per Chip']  * ssj2008['Chips'] == ssj2008['Total Cores']]

Empty DataFrame
Columns: [Suite, HW Vendor, System Name, Test Date, HW Avail, Result, CPU Name, CPU Characteristics, CPU MHz, CPU Enabled, Total Threads, CPU Orderable, L1 Cache, L2 Cache, L3 Cache, Memory Amount, # and size of DIMM, Memory, Storage, OS, OS Version, File System, JVM Vendor, JVM Version, URL Suffix, Total Cores, Chips, Cores Per Chip]
Index: []

[0 rows x 28 columns]

In [31]:
ssj2008['Memory Amount'].unique()

array([ 192.,   16.,    8.,   12.,  768.,   32.,  256.,  512.,  384.,
         64.,   24.,  128.,   96.,    4.,  196.,   48.,   60.,    6.,
       1536.,   18.])

In [14]:
ssj2008_rename_dict = {
    'Hardware Vendor': 'HW Vendor',
    'Model': 'System Name',
    'Hardware Availability': 'HW Avail',
    'Benchmark': 'Result',
    'CPU Frequency (MHz)': 'CPU MHz', 
    'CPU(s) Enabled': 'CPU Enabled',
    'CPU(s) Orderable': 'CPU Orderable',
    'Primary Cache': 'L1 Cache',
    'Secondary Cache': 'L2 Cache',
    'Tertiary Cache': 'L3 Cache',
    'Memory Amount (GB)': 'Memory Amount',
    'Memory Details': 'Memory',
    'Disk Drive': 'Storage',
    'Operating System (OS)': 'OS',
    'Filesystem': 'File System',
}

In [15]:
ssj2008.rename(columns=ssj2008_rename_dict, inplace=True)

In [16]:
ssj2008.columns

Index(['Suite', 'HW Vendor', 'System Name', 'Test Date', 'HW Avail', 'Result',
       'CPU Name', 'CPU Characteristics', 'CPU MHz', 'CPU Enabled',
       'Total Threads', 'CPU Orderable', 'L1 Cache', 'L2 Cache', 'L3 Cache',
       'Memory Amount', '# and size of DIMM', 'Memory', 'Storage', 'OS',
       'OS Version', 'File System', 'JVM Vendor', 'JVM Version', 'URL Suffix'],
      dtype='object')

In [32]:
ssj2008['Memory Amount'].dtype

dtype('float64')

In [ ]:
ssj2008[['OS', ' Version']]

OS  \
0    Microsoft Windows Server 2012 R2 Datacenter   
1        Windows Server 2008, Enterprise Edition   
2        Windows Server 2008, Enterprise Edition   
3        Windows Server 2008, Enterprise Edition   
4        Windows Server 2008, Enterprise Edition   
..                                           ...   
773          SUSE Linux Enterprise Server 12 SP4   
774     Microsoft Windows Server 2019 Datacenter   
775  Microsoft Windows Server 2012 R2 Datacenter   
776          SUSE Linux Enterprise Server 12 SP4   
777  Microsoft Windows Server 2012 R2 Datacenter   

                            OS Version  
0             Version 6.3 (Build 9600)  
1                                   R2  
2                                   R2  
3                                   R2  
4                                   R2  
..                                 ...  
773              4.12.14-94.41-default  
774  Version 1809 (OS Build 17763.720)  
775           Version 6.3 (Build 9600)  
776              4.12.14-94.41-default  
777           Version 6.3 (Build 9600)  

[778 rows x 2 columns]

In [34]:
ssj2008[['Test Date', 'HW Avail']]

Test Date  HW Avail
0    Sep 26, 2018  Sep-2018
1    Oct 20, 2010  Oct-2010
2     Oct 5, 2010  Aug-2010
3     Oct 5, 2010  Aug-2010
4    Sep 29, 2010  Oct-2010
..            ...       ...
773  Nov 22, 2019  Oct-2019
774  Nov 21, 2019  Oct-2019
775   May 9, 2019  Apr-2019
776  Jun 11, 2019  Apr-2019
777  Jan 10, 2019  Jan-2019

[778 rows x 2 columns]

In [28]:
ssj2008[['JVM Vendor', 'JVM Version']]

JVM Vendor                                        JVM Version
0    Oracle Corporation  Oracle Java HotSpot(TM) 64-Bit Server VM (buil...
1       IBM Corporation  IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Win...
2       IBM Corporation  IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Win...
3       IBM Corporation  IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Win...
4       IBM Corporation  IBM J9 VM <build 2.4, JRE 1.6.0 IBM J9 2.4 Win...
..                  ...                                                ...
773              Oracle  Oracle Java HotSpot(TM) 64-Bit Server VM (buil...
774              Oracle  Java HotSpot(TM) 64-Bit Server VM (build 12.0....
775  Oracle Corporation  Oracle Java HotSpot(TM) 64-Bit Server VM (buil...
776  Oracle Corporation  Oracle Java HotSpot(TM) 64-Bit Server VM (buil...
777  Oracle Corporation  Oracle Java HotSpot(TM) 64-Bit Server VM (buil...

[778 rows x 2 columns]

In [26]:
ssj2008[['Memory Amount', '# and size of DIMM']]

Memory Amount # and size of DIMM
0            192.0         12 x 16 GB
1             16.0        8 x 2048 MB
2             16.0        8 x 2048 MB
3             16.0        8 x 2048 MB
4              8.0        2 x 4096 MB
..             ...                ...
773          128.0          8 x 16 GB
774          128.0          8 x 16 GB
775          192.0         12 x 16 GB
776          192.0         12 x 16 GB
777          192.0         12 x 16 GB

[778 rows x 2 columns]

In [25]:
ssj2008['Memory Amount'].unique()

array([ 192.,   16.,    8.,   12.,  768.,   32.,  256.,  512.,  384.,
         64.,   24.,  128.,   96.,    4.,  196.,   48.,   60.,    6.,
       1536.,   18.])

In [23]:
ssj2008['# and size of DIMM'].unique()

array(['12 x 16 GB', '8 x 2048 MB', '2 x 4096 MB', '6 x 2048 MB',
       '4 x 4096 MB', '4 x 2048 MB', '1 x 16 GB', '24 x 32 GB',
       '4 x 8 GB', '16 x 16384 MB', '16 x 32 GB', '12 x 32 GB',
       '8 x 4096 MB', '8 x 8192 MB', '6 x 4096 MB', '8 x 8 GB',
       '8 x 16384 MB', '4 x 2GB', '4x2GB', '4x 2GB', '4x4GB', '4x 4GB',
       '16 x 8 GB', '8 x 16 GB', '4x2048 MB', '4x4096 MB',
       '12 x 16384 MB', '12 x 8 GB', '2 x 8192 MB', '4 x 2 GB',
       '4 x 4 GB', '4 x 16 GB', '16 x 16 GB', '24 x 16 GB',
       '32 x 4096 MB', '16 x 8192 MB', '16 x 4096 MB', '2 x 2048 MB',
       '2 x 4 GB', '24 x 16384 MB', '6 x 16384 MB', '48 x 16 GB',
       '2 x 16 GB', '4x1GB', '2 x 4GB', '4 x 1024 MB', '12 x 4096 MB',
       '6 x 4098 MB', '4x4096MB PC2-5300F', '6 x 8 GB', '6 x 4 GB',
       '15 x 4 GB', '8 x 4 GB', '12 x 4 GB', '6 x 2 GB', '2 x 4096 GB',
       '4 x 8192 MB', '6 x 8192 MB', '6 x 1024 MB', '16 x 1024 MB',
       '16 x 2048 MB', '4 x 2048 GB', '4 x 4096 GB',
       '2x4096 MB, 